package io.github.serivesmejia.TicTacToe;

import static io.github.serivesmejia.TicTacToe.TicTacToe.sSyst;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author Sebastian
 */
public class frame extends javax.swing.JFrame implements KeyListener{
    public int turn = 0;
    public int clicked = 0;
    public static HashMap game = new HashMap();
    public static Boolean restart = false;

    
    public frame() {       
        addKeyListener(this);
        initComponents();
        setSize(224, 412);
        jButton10.setOpaque(true);
        ImageIcon icon = new ImageIcon(getClass().getResource("R.png"));
        ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
        jButton10.setIcon(icons);
        
        requestFocusInWindow();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("X.png")));
        setTitle("Tic Tac Toe");
        

        setDefaultLookAndFeelDecorated(true);
        setResizable(false);
        setLocationRelativeTo(null);     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton9KeyPressed(evt);
            }
        });

        jButton10.setEnabled(false);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton10KeyPressed(evt);
            }
        });

        jLabel1.setText("Turno: X");

        jMenu1.setText("Juego");
        jMenu1.setToolTipText("");

        jMenuItem2.setText("Jugar vs CPU");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Estadisticas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator3);

        jMenuItem4.setText("Acerca de");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventana");

        jMenuItem1.setText("Minimizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(6) != "D"){
            
        }else{
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
            clicked = clicked + 1;
            jButton10.setEnabled(true);
            if(turn == 0){
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(6, "X");
                jLabel1.setText("Turno: O");
                jButton6.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(6, "O");
                jLabel1.setText("Turno: X");
                jButton6.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(1) != "D"){
 
        }else{
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            jButton10.setEnabled(true);
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(1, "X");
                jButton1.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(1, "O");
                jLabel1.setText("Turno: X");
                jButton1.setIcon(icons);
            }
            check();            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(2) != "D"){

        }else{
            
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(2, "X");
                jButton2.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(2, "O");
                jLabel1.setText("Turno: X");
                jButton2.setIcon(icons);
            }
            check();
        }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(3) != "D"){

        }else{
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(3, "X");
                jButton3.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                jLabel1.setText("Turno: X");
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(3, "O");
                jButton3.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(4) != "D"){

        }else{
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(4, "X");
                jButton4.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                jLabel1.setText("Turno: X");
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(4, "O");
                jButton4.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(5) != "D"){
        }else{
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(5, "X");
                jButton5.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                jLabel1.setText("Turno: X");
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(5, "O");
                jButton5.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(7) != "D"){
        }else{
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(7, "X");
                jButton7.setIcon(icons);
            }else if(turn == 1){
                jLabel1.setText("Turno: X");
                turn = 0;
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(7, "O");
                jButton7.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        if(game.get(8) != "D"){
        }else{
            
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(8, "X");
                jButton8.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                jLabel1.setText("Turno: X");
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(8, "O");
                jButton8.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        TicTacToe.cfg.replace("clicks", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("clicks")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        if(game.get(9) != "D"){
        }else{          
            jButton10.setEnabled(true);
            sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
             clicked = clicked + 1;
            if(turn == 0){
                jLabel1.setText("Turno: O");
                turn = 1;
                ImageIcon icon = new ImageIcon(getClass().getResource("X.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(9, "X");
                jButton9.setIcon(icons);
            }else if(turn == 1){
                turn = 0;
                jLabel1.setText("Turno: X");
                ImageIcon icon = new ImageIcon(getClass().getResource("O.png"));
                ImageIcon icons = new ImageIcon(icon.getImage().getScaledInstance(30, -1, 1));
                game.replace(9, "O");
                jButton9.setIcon(icons);
            }
            check();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
     
    }//GEN-LAST:event_formKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
      if(evt.getKeyCode() == 36){
                jButton1ActionPerformed(null);
      }
     if(evt.getKeyCode() == 38){
                jButton2ActionPerformed(null);
      }
     if(evt.getKeyCode() == 33){
                jButton3ActionPerformed(null);
      }
     if(evt.getKeyCode() == 37){
                jButton4ActionPerformed(null);
     }
     if(evt.getKeyCode() == 12){
                jButton5ActionPerformed(null);
      }  
     if(evt.getKeyCode() == 39){
                jButton6ActionPerformed(null);
     }    
     if(evt.getKeyCode() == 35){
                jButton7ActionPerformed(null);
     }   
     if(evt.getKeyCode() == 40){
                jButton8ActionPerformed(null);
     }   
     if(evt.getKeyCode() == 34){
                jButton9ActionPerformed(null);
     }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
        restart();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton8KeyPressed

    private void jButton9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton9KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton9KeyPressed

    private void jButton10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton10KeyPressed
        jButton1KeyPressed(evt);
    }//GEN-LAST:event_jButton10KeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        sSyst.cleanup();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        restart();
        setVisible(false);
        String[] args = null;
        frame_cpu.main(args);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setState(ICONIFIED);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String[] args = null;
        statsFrame.main(args);
        sSyst.backgroundMusic("/PopSoundEffect.ogg", frame.class.getResource("/PopSoundEffect.ogg") , "/PopSoundEffect.ogg", false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    String appdata = System.getenv("APPDATA");  
    
public boolean check(){
    if(game.get(9) == "X" && game.get(1) == "X" && game.get(5) == "X"){
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        String[] args = null;
        Message.msg = "  X ha ganado! 1";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;
    }else if(game.get(1) == "X" && game.get(2) == "X" && game.get(3) == "X"){
        String[] args = null;
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        Message.msg = "  X ha ganado! 2";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true; 
    }else if(game.get(4) == "X" && game.get(5) == "X" && game.get(6) == "X"){
       String[] args = null;
       TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        Message.msg = "  X ha ganado! 3";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;  
    }else if(game.get(7) == "X" && game.get(8) == "X" && game.get(9) == "X"){
      String[] args = null;
      TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        Message.msg = "  X ha ganado! 4";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;   
    }else if(game.get(3) == "X" && game.get(5) == "X" && game.get(7) == "X"){
       String[] args = null;
       TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        Message.msg = "  X ha ganado! 5";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;    
    }else if(game.get(1) == "X" && game.get(4) == "X" && game.get(7) == "X"){
        String[] args = null;
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        Message.msg = "  X ha ganado! 6";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;    
    }else if(game.get(2) == "X" && game.get(5) == "X" && game.get(8) == "X"){
       String[] args = null;
       TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        Message.msg = "  X ha ganado! 7";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;     
    }else if(game.get(3) == "X" && game.get(6) == "X" && game.get(9) == "X"){
      String[] args = null;
      TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("XW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("XW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);    
        
        Message.msg = "  X ha ganado! 8";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;   
    //oooo
    }else if(game.get(9) == "O" && game.get(1) == "O" && game.get(5) == "O"){
        String[] args = null;
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("OW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("OW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        Message.msg = "  O ha ganado! 1";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;
    }else if(game.get(1) == "O" && game.get(2) == "O" && game.get(3) == "O"){
        String[] args = null;
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("OW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("OW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        Message.msg = "  O ha ganado! 2";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true; 
    }else if(game.get(4) == "O" && game.get(5) == "O" && game.get(6) == "O"){
       String[] args = null;
       TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        Message.msg = "  O ha ganado! 3";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;  
    }else if(game.get(7) == "O" && game.get(8) == "O" && game.get(9) == "O"){
      String[] args = null;
      TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("OW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("OW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        Message.msg = "  O ha ganado! 4";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;   
    }else if(game.get(3) == "O" && game.get(5) == "O" && game.get(7) == "O"){
       String[] args = null;
       TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("OW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("OW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        Message.msg = "  O ha ganado! 5";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;    
    }else if(game.get(1) == "O" && game.get(4) == "O" && game.get(7) == "O"){
        String[] args = null;
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("OW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("OW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        Message.msg = "  O ha ganado! 6";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;    
    }else if(game.get(2) == "O" && game.get(5) == "O" && game.get(8) == "O"){
       String[] args = null;
       TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        Message.msg = "  O ha ganado! 7";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;     
    }else if(game.get(3) == "O" && game.get(6) == "O" && game.get(9) == "O"){
      String[] args = null;
      TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("OW", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("OW")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        Message.msg = "  O ha ganado! 8";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true; 
     }  
    
    if(clicked == 9){
        TicTacToe.cfg.replace("plays", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("plays")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);
        
        TicTacToe.cfg.replace("ties", String.valueOf(Integer.parseInt((String) TicTacToe.cfg.get("ties")) + 1));
        TicTacToe.DumpWriterCFG(new File(appdata + "\\TicTac-s\\stats.yml"), TicTacToe.cfg);        
        
        String[] args = null;
        Message.msg = "       Empate!";
        Message.main(args);
        clicked = 0;
        turn = 0;
        return true;       
    }
    
    
    return false;
    
}

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println(e.getKeyCode());
    }

    @Override
    public void keyReleased(KeyEvent k) {
        
    }

public void restart(){
    game.clear();
    jButton10.setEnabled(false);
    jLabel1.setText("Turno: X");
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("X.png")));

    jButton1.setIcon(null);
    jButton2.setIcon(null);
    jButton3.setIcon(null);
    jButton4.setIcon(null);
    jButton5.setIcon(null);
    jButton6.setIcon(null);
    jButton7.setIcon(null);
    jButton8.setIcon(null);
    jButton9.setIcon(null);
    clicked = 0;
    turn = 0;
    
    int count = 1;
    while(count < 10){
        frame.game.put(count, "D"); 
        count = count + 1;
    }
}

}
